# Generated by Django 5.0.6 on 2025-03-17 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_full_name', models.CharField(max_length=255)),
                ('delivery_email', models.EmailField(default='default@gmail.com', max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_phone_number', models.CharField(max_length=12)),
                ('delivery_city', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_district', models.CharField(blank=True, max_length=255, null=True)),
                ('details_about_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'DeliveryAddress',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='default@gmail.com', max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('company_info', models.TextField(default='Electrogram LLC\nellectrogramllc.com\nTel: (+256 752235731)\nHome Of Electronics')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
