# Generated by Django 5.0.6 on 2025-05-23 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='delivery_phone_number',
            field=models.CharField(help_text='Enter phone number with country code (e.g., +256XXXXXXXXX)', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +256XXXXXXXXX', regex='^\\+256\\d{9}$')]),
        ),
    ]
