# Generated by Django 5.0.6 on 2025-03-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DailyOffer', 'Daily Offer'), ('Recent', 'Recent Product'), ('BestSelling', 'Best Selling Product'), ('Weekly', 'Weekly Product'), ('Monthly', 'Monthly Product'), ('Flash', 'Flash Product'), ('Special', 'Special Product')], max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='base.tag'),
        ),
    ]
